### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by whatisgravity** [wduan2/amg#2]
I believe the dependencies should be listed inside the gemspec. It currently requires at least crack and ap. Ill list all of them when I get it working.

**Comment by whatisgravity** [comment]
Final list

crack
ap
colorize
mysql2 -- you should really switch to leveldb or something similar embedded DB. mysql is way to heavy weight for a simple cli tool. put me off using it unitl I can switch the DB out.

**Comment by wduan2** [comment]
Good catch, I've committed a fix. Thank you !

**Comment by wduan2** [comment]
@whatisgravity I will try to switch to SQLite in the following days. MySQL is definitely cumbersome here.
